name: Build and push docker image to ECR
on: 
    push:  
      branches:
        - main
    workflow_dispatch:
jobs: 
    build-docker:
        runs-on: ubuntu-latest
        steps:
           - uses: actions/checkout@v7 
