# Name shown in github actions
name: Build infrastructure and deploy to AWS ECS

# Only run by manual trigger for now, can be changed to push to main branch later
on: 

    workflow_dispatch:

# Give the workflow permissions to request an OIDC token and read the repository contents
permissions: 
    id-token: write
    contents: read

# Define the jobs to run in this workflow
jobs: 
    build-infra:
        runs-on: ubuntu-latest

# Download the repository so the runner can access the Terraform files
        steps:
           - name: checkout code 
             uses: actions/checkout@v7 

           - name: Checkov Terraform security scan
             uses: bridgecrewio/checkov-action@v12
             with:
                directory: ./infrastructure
                framework: terraform

